name: go-linker docker publish

on:
  push:
    paths:
      - 'go-linker/**'
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        run: |
          export COMMIT_ID=$(git rev-parse --short=7 "$GITHUB_SHA")
          export IMAGE_NAME="docker.pkg.github.com/${{ github.repository }}/go-linker"
          docker buildx create --use
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_NAME:$COMMIT_ID \
            --tag $IMAGE_NAME:latest .

      - name: Set up Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image to GitHub Packages
        run: docker push ${{ steps.docker_build.outputs.image }}
